# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoCutterDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PhotoCutterDemo

pod 'Masonry'
pod 'YYCategories'
  target 'PhotoCutterDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoCutterDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
